# Generated by Django 3.0.5 on 2020-09-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Oficina', 'Oficina'), ('Residencial', 'Residencial'), ('Comercial', 'Comercial')], max_length=150, null=True)),
                ('contenido', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='Proyectos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
