# Generated by Django 3.0.5 on 2020-09-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='type',
            field=models.CharField(choices=[('Of', 'Oficina'), ('Res', 'Residencial'), ('Com', 'Comercial')], max_length=150, null=True),
        ),
    ]
